trigger:
  - main

name: spots-userservice - $(Date:yyyyMMdd)$(Rev:.rr)

stages:
  - stage: Build_Test
    jobs:
      - job:
        displayName: Build spots-userservice
        steps:
          - task: Gradle@2
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'build'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              sonarQubeRunAnalysis: false
  - stage: Create_Images
    jobs:
        - job:
          displayName: Create Gradle Image

          variables:
          - name: image
            value: imageNotSpecified 
          - name: tag
            value: tagNotSpecified 

          steps:
          - task: Gradle@2
            displayName: Build Docker image (Jib)
            inputs:
              gradleWrapperFile: 'gradlew'
              tasks: 'clean jibDockerBuild -x test'
              publishJUnitResults: false
              jdkVersionOption: '1.11'
          - task: PowerShell@2
            displayName: Retrieve Image Data
            inputs:
              targetType: 'inline'
              script: |
                $gradle = Get-Content .\build.gradle
                $image="spots-userservice"
                $tag="0.0.1-SNAPSHOT"
                Write-Host "##vso[task.setvariable variable=image]$image"
                Write-Host "##vso[task.setvariable variable=tag]$tag"
              showWarnings: true
              # workingDirectory: ${{ parameters.workingDirectory }}
          - task: Docker@2
            displayName: Push Docker image
            inputs:
              containerRegistry: 'spotsregistry1'
              repository: $(image)
              command: 'push'
              tags: |
                latest